### PR TITLE
Prevent hashing strings.

### LINKED ISSUE #5: Hashes strings wrong
Hi. I noticed hashing strings is incorrect. It hashes the zeroed input buffer instead:

```js
blake2b(16).update('a').digest('hex')
// '7025e075d5e2f6cde3cc051a31f07660'

blake2b(16).update('b').digest('hex')
// '7025e075d5e2f6cde3cc051a31f07660'

blake2b(16).update(new Uint8Array(1)).digest('hex')
// '7025e075d5e2f6cde3cc051a31f07660'
```

Based on `hash.update` and `blake2bUpdate`, the effect seems to be like:

```js
const arr = new Uint8Array(1)
arr[0] = 'a'
// that does nothing:
// arr[0] === 0
blake2b(16).update(arr).digest('hex')
// '7025e075d5e2f6cde3cc051a31f07660'
```

Related to this issue is hashing empty strings:

```js
blake2b(16).update('').digest('hex')
// Error: input must be TypedArray or Buffer
```

Maybe this assert was intended for all strings, and not just the empty one? It could also use `TextEncoder` and `Buffer.from` for you.

### PR DESCRIPTION
**Pull request by jamen**
Fixes https://github.com/emilbayes/blake2b/issues/5

Please see https://github.com/mafintosh/blake2b-wasm/pull/12 which fixes the same issue in the WASM module.

### CODE REVIEW

**Comment by emilbayes** [comment]
I was wondering if we could use [`Symbol.spieces`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol/species) to be more precise?

**Comment by jamen** [comment]
The test would be kind of long:

```js
assert(input instanceof ArrayBuffer || (typeof Buffer !== 'undefined' && input instanceof Buffer))
```

The `typeof` thing is necessary because `Buffer` would throw an error on browser.

Is that fine? Or do you have a better idea? I wanted to keep the overhead in the hashing to a minimum.

**Comment by emilbayes** [comment]
Simply doing `input instanceof Uint8Array` would suffice :)

**Comment by jamen** [comment]
TIL that works on regular buffers.

```js
Buffer.from('a') instanceof Uint8Array === true
```

Thanks. Pushed a new commit.

**Comment by emilbayes** [comment]
Nice! Do you want to do the same for the constructor and digest functions? Then you get full credit :)

**Comment by jamen** [comment]
Sorry for going cold on this.  I added asserts for constructor and digest, and made the messages more accurate for what its checking.

**Comment by jamen** [comment]
I don't understand why the test fails on node 8 and latest, but seems like it was already happening.

File: index.js [hunk 1]
```diff
@@ -221,6 +221,7 @@ Blake2b.prototype.digest = function (out) {
   assert(buf.length >= this.outlen, 'out must have at least outlen bytes of space')
   blake2bFinal(this, buf)
   if (out === 'hex') return hexSlice(buf)
+  assert(buf instanceof Uint8Array, 'input must be Uint8Array or Buffer')
```
Comment (emilbayes) [inline index.js]: Can you move this up under the other assert? It's too late to assert it at that point since it has already been attempted to be written to :) Then this is good to merge!

Comment (jamen) [reply index.js]: Fixed

**Comment by emilbayes** [comment]
This is great thank you!

Maybe you want to submit a similar PR to the wasm impl? Otherwise I'll do it

**Comment by jamen** [comment]
@emilbayes Thanks. I've done that in mafintosh/blake2b-wasm#12. Let me know if I need to change something.
